/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`.
// It's checked in here so the project type-checks immediately after
// `npm install`, before you've run Next.js for the first time.
